### PR TITLE
Drop only existing foreign_keys

### LINKED ISSUE #239: Puppet disable command fails
Fails with error:

Running Remove Puppet feature
================================================================================
Check for Puppet capsules from the database:                          [OK]
--------------------------------------------------------------------------------
Remove Puppet feature:                                                [FAIL]
Failed executing foreman-rake db:migrate VERSION=0 SCOPE=foreman_puppet, exit status 1:
 rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Table 'host_classes' has no foreign key for hosts

cloned from Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2032928

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Fixes #239

### CODE REVIEW

**Review by vsedmik — APPROVED** [review]
ACK this patch fixed the issue

File: db/migrate_foreman/20120824142048_add_some_indexes.foreman_puppet.rb [hunk 1]
```diff
@@ -13,9 +13,9 @@ def up
   end
 
   def down
-    remove_foreign_key 'host_classes', 'hosts', name: 'host_classes_host_id_fk'
-    remove_foreign_key 'host_classes', 'puppetclasses', name: 'host_classes_puppetclass_id_fk'
-    remove_foreign_key 'operatingsystems_puppetclasses', 'operatingsystems', name: 'operatingsystems_puppetclasses_operatingsystem_id_fk'
-    remove_foreign_key 'operatingsystems_puppetclasses', 'puppetclasses', name: 'operatingsystems_puppetclasses_puppetclass_id_fk'
+    remove_foreign_key('host_classes', 'hosts') if foreign_key_exists?(:host_classes, :hosts)
```
Comment (nadjaheitmann) [inline db/migrate_foreman/20120824142048_add_some_indexes.foreman_puppet.rb:16]: Any idea whether this error can occur for the other migrations?

**Comment by nadjaheitmann** [comment]
Could you please add a more descriptive commit message :)

File: db/migrate_foreman/20120824142048_add_some_indexes.foreman_puppet.rb (hunk 1 above)
Comment (ezr-ondrej) [reply db/migrate_foreman/20120824142048_add_some_indexes.foreman_puppet.rb:16]: no idea if it can, it didn't in Satellite usecase, but I can add the condition to all of them :)

Comment (nadjaheitmann) [reply db/migrate_foreman/20120824142048_add_some_indexes.foreman_puppet.rb:16]: Won't hurt I guess :) Any idea why the error occurred in the first place?

**Comment by ezr-ondrej** [comment]
Better? :)

File: db/migrate_foreman/20120824142048_add_some_indexes.foreman_puppet.rb (hunk 1 above)
Comment (ezr-ondrej) [reply db/migrate_foreman/20120824142048_add_some_indexes.foreman_puppet.rb:16]: I believe it was because of the FK was created with the table alrady and thus had a default name, not the name given by us.

**Comment by nadjaheitmann** [comment]
LGTM! Thanks @ezr-ondrej

**Review by nadjaheitmann — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
CP 2.0: 6b5f43a
