### PR TITLE
Do not create table under old name

### LINKED ISSUE #246: Migration fails for upgrades
Upgrade to 3.1 - db:migrate fails with PG::DuplicateTable

`PG::DuplicateTable: ERROR:  relation "index_hostgroups_puppetclasses_on_hostgroup_id" already exists`

Details in https://community.theforeman.org/t/upgrade-to-3-1-db-migrate-fails-with-pg-duplicatetable/26720

### PR DESCRIPTION
**Pull request by ezr-ondrej**
The migration from foreman is creating the hostgroups table under its old name
This causes the check for its existence to pass, even though it exists.

Fixes #246

### CODE REVIEW

File: db/migrate_foreman/20090905150132_create_hostgroups_puppetclasses.foreman_puppet.rb [hunk 1]
```diff
@@ -1,6 +1,8 @@
 class CreateHostgroupsPuppetclasses < ActiveRecord::Migration[6.0]
   def up
-    create_table :hostgroups_puppetclasses, id: false, if_not_exists: true do |t|
+    # this table is later renamed into hostgroup_classes and thus we don't want to create it if it exists under the later name
+    return if table_exists?(:hostgroups_puppetclasses) || table_exists?(:hostgroups_classes)
```
Comment (tjikkun) [inline db/migrate_foreman/20090905150132_create_hostgroups_puppetclasses.foreman_puppet.rb:4]: `hostgroup_classes`

Comment (ezr-ondrej) [reply db/migrate_foreman/20090905150132_create_hostgroups_puppetclasses.foreman_puppet.rb]: Thanks :heart: fixed :+1:

**Comment by nadjaheitmann** [comment]
LGTM. Test failure is unrelated, isn't it?

**Comment by tjikkun** [comment]
This PR fixes it for me

**Comment by ezr-ondrej** [comment]
> LGTM. Test failure is unrelated, isn't it?

Yeah, those are unrelated, I'm trying to fix them in #249, but it will take time. Tho this is not tested anyways, so let's get that in.

**Review by nadjaheitmann — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
CP 2.0: 2c2ab49
