### PR TITLE
Fixes issue 325 - Correct untranslatable welcome string

### LINKED ISSUE #325: Untranslatable string
This string can't be translated:
https://github.com/theforeman/foreman_puppet/blob/41ab916bbbc78cfdaff8fa7723df88165f31cbda/webpack/src/Components/Environments/Welcome.js#L13-L16

It's **always** invalid to use ```__(````.

_Originally posted by @ekohl in https://github.com/theforeman/foreman_puppet/pull/323#discussion_r1050737749_

### PR DESCRIPTION
**Pull request by nadjaheitmann**
I did the fix based on https://github.com/theforeman/foreman/commit/57a4506c6060dbf34e6b94e322c2316b1d50a808

Please check if there is anything I missed.

### CODE REVIEW

**Review by Ron-Lavi — APPROVED** [review]
Thanks @nadjaheitmann !

File: webpack/src/Components/Environments/Welcome.js [hunk 1]
```diff
@@ -10,16 +11,34 @@ export const WelcomeEnv = ({ canCreate }) => {
...
-  const content = __(`If you are planning to use Foreman as an external node classifier you should provide information about one or more environments.<br/>
-  This information is commonly imported from a pre-existing Puppet configuration by the use of the <a target="_blank" href=${getManualURL(
-    '4.2.2Classes'
-  )}>Puppet classes and environment importer.</a>`);
+  const description = (
+    <>
+      <FormattedMessage
+        id="puppetenv-welcome"
+        defaultMessage={__(
+          'If you are planning to use Foreman as an external node classifier you should provide information about one or more environments.{newLine}This information is commonly imported from a pre-existing Puppet configuration by the use of the {puppetClasses}.'
```
Comment (ekohl) [inline webpack/src/Components/Environments/Welcome.js:19]: Late to the party, so sorry about that.

You have improved it, but you still have made something that's very hard to translate because you string parts of a sentence together. In a language where the word order is not the same it may be incomprehensible for the reader.

What I think you should probably do is have a `{link-start}` and `{link-end}` placeholder so translators have the freedom to move it around.

Comment (ekohl) [reply webpack/src/Components/Environments/Welcome.js:19]: Oh, and sadly we can't extract multi-line strings now so this string doesn't show up in the .pot file.

**Comment by nadjaheitmann** [comment]
Thanks @ekohl for your comments. It would be nice to have those information in the translations guide: https://projects.theforeman.org/projects/foreman/wiki/Translating

**Comment by ekohl** [comment]
Yes, I'm slowly collecting my thoughts on that, but it's also taking me a while to grasp. Right now I'm collecting the issues and seeing which ones we should be solving at the core (like the multi-line string extraction) and the ones you as the author must be aware of (like stringing together sentences). Thanks for sticking with it.
